version: 0.2

phases:
  build:
    commands:
      - echo "$PRIVATE_KEY_B64" | base64 -d > key.pem
      - chmod 400 key.pem
      - ssh -vvv -i key.pem -o StrictHostKeyChecking=no ubuntu@13.201.84.15 "echo connected"
